[build]
  command = "npm run build"
  publish = "dist"

# SPA routing (React Router miatt)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Fix MIME / headers (opcionális, de segíthet)
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"